### PR TITLE
renames randoom-release-version.jar to randoop.jar

### PR DESCRIPTION
**Pull request by hsanchez**
@martinschaef ... please review this pull request.

### CODE REVIEW

**Comment by martinschaef** [comment]
Did you check the output? The travis log is a bit too long to read on my phone ;)

**Comment by hsanchez** [comment]
@martinschaef 

Yes, I checked the output before and after my changes. They seemed the same. I even got the same typical implementations (last step) of sorting..  is there something you noticed that I should check? Let me know.

**Comment by martinschaef** [comment]
Wow, why didn't I see that until now?

**Comment by hsanchez** [comment]
@martinschaef Maybe because you started paying more attention to integration-test2? That happened to me (e.g., I forgot I've created this pull request....) :-)

**Pull request merged**
